### ISSUE TITLE
Problem with POST to create report

### ISSUE THREAD

**Issue by Stiuzz** [dynatrace-oss/PTC-Windchill#1]
Probably due to some changes in Dynatrace's API implementation the dasbord's owner MUST be declared in the JSOM file.
I resolved the issue adding the owner in dashboardMetadata section:
"owner":"admin",

A user should at least add himself to view (and eventually share) the dashboards

Regards
Stiuzz

**Comment by Dynatrace-Asad-Ali** [comment]
This is fixed in the latest release.
