### ISSUE TITLE
Dashboard import failed

### ISSUE THREAD

**Issue by aborowicz-ttpsc** [dynatrace-oss/PTC-Windchill#3]
Hi,
Just wanted to let you know that during an import, all dashbords prompt an error message:

Saving failed: Non numeric dimension id '75f4744d-c714-49fc-99de-82635253cb9a' for metric 'builtin -> tech -> jvm -> threads -> totalCpuTime',Tiles configuration is invalid.

Best regards,
Aleksander

**Comment by Dynatrace-Asad-Ali** [comment]
It looks like a bug in Dynatrace UI. Please use the REST API to create dashboards.
