### ISSUE TITLE
CustomServices import issue

### ISSUE THREAD

**Issue by aborowicz-ttpsc** [dynatrace-oss/PTC-Windchill#5]
Checkin and Checkout after imports are not seeing arguments for chart results/ no available services

Best regards,
Aleksander

**Comment by Dynatrace-Asad-Ali** [comment]
Aleksander,
The dashboard D202 should bring data for checkin and checkout by username. Do you not see it?

**Comment by Dynatrace-Asad-Ali** [comment]
I have uploaded a newer version of the dashboard D202-Workspace Operations. Please use that dashboard to resolve this issue.
